version: "3.8"

services:
  shop:
    container_name: shop
    build:
      context: .
      dockerfile: docker/store/Dockerfile
    networks:
      - webnet
      - nginx_network
    expose:
      - 8000
    environment:
      DATABASE_NAME: 'dbshop'
      DATABASE_PORT: '5432'
      DJANGO_ENV: 'dev'
    volumes:
      - ./store/:/code
    restart: on-failure
    command: sh /runserver.sh
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://0.0.0.0:8000/admin/login/" ]
      interval: 1m
      timeout: 5s
      retries: 2

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    restart: on-failure
    networks:
      - nginx_network
    ports:
     - 80:80
    depends_on:
      - shop
    healthcheck:
      test: [ "CMD-SHELL", "ps ax", "|" ,"grep -v grep", "|" ,"grep nginx",  "||", "exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3


  db:
    container_name: db
    image: postgis/postgis:12-master
    restart: on-failure
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - webnet
    expose:
      - 5432
    environment:
      POSTGRES_DB: 'dbshop'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgdb'

    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  db-data:

networks:
  nginx_network:
  webnet: