# Generated by Django 3.2.6 on 2021-09-02 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_userbase_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userbase',
            managers=[
            ],
        ),
    ]
