# Generated by Django 3.2.7 on 2021-11-08 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_auto_20211027_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='author',
            name='slug',
            field=models.SlugField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='publication_year',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateField(blank=True, help_text='Date when order was created', null=True, verbose_name='order date'),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_status', models.PositiveSmallIntegerField(choices=[(1, 'Reserved'), (2, 'In stock'), (3, 'Sold')], default=2)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.book')),
                ('item_of_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.orderitem')),
            ],
        ),
    ]
