# Generated by Django 3.2.7 on 2021-11-20 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_remove_author_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='bio',
        ),
    ]
