# Generated by Django 3.2.7 on 2021-11-20 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_alter_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
