# Generated by Django 3.2.9 on 2021-11-26 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_book',
        ),
    ]
