# Generated by Django 3.2.6 on 2021-11-26 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='totalrating',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='book',
            name='totalreview',
            field=models.IntegerField(default=1),
        ),
    ]
